// next-front/app/components/UsernameInput.jsx
"use client"
import React, { useState } from 'react'; // Import useState for state management

const UsernameInput = ({ modelValue, serverErrors, ...rest }) => {
  const [username, setUsername] = useState(modelValue); // Use state for username

  const handleChange = (event) => {
    setUsername(event.target.value);
    // Emit the update event if needed (replace with your event handling)
    // rest.onChange && rest.onChange(event.target.value);
  };

  return (
    <div>
      <input
        type="text"
        className="form-control form-control-lg"
        id="username"
        placeholder="نام کاربری"
        value={username}
        onChange={handleChange}
        {...rest} // Pass through any additional props
        className={`${rest.className || ''} ${serverErrors ? 'is-invalid' : ''}`} // Combine classNames
      />
      {serverErrors && (
        <div className="invalid-feedback text-right">{serverErrors}</div>
      )}
    </div>
  );
};

export default UsernameInput;

// nuxt-front/components/UsernameInput.vue
<template>
  <ValidationProvider rules="required" vid="username" v-slot="{ errors }">
    <input
      type="text"
      class="form-control form-control-lg"
      id="username"
      placeholder="نام کاربری"
      :class="(errors[0] || serverErrors )? 'is-invalid' : ''"
      v-model="value"
      v-on:input="$emit('input', $event.target.value)"
    />

    <div class="invalid-feedback text-right">
      {{ errors[0] || serverErrors}}
    </div>
  </ValidationProvider>
</template>

<script>
import { ValidationProvider, extend } from "vee-validate";
import { required,} from "vee-validate/dist/rules";

extend("required", required);


extend("required", {
  ...required,
  message: "لطفا این فیلد را تکمیل کنید",
});

export default {
  props: ["value", "serverErrors"],
  components: {
    ValidationProvider,
  },
};
</script>

<style>
</style>
