// next-front/app/(notes)/pp/page.jsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { Pagination } from 'react-bootstrap';
import NoteList from '../../components/NoteList';
import { handleApiError } from '@/app/utils/errorHandler';

export default function PaginatedNoteList({ initialNotes = [] }) {
  const [notes, setNotes] = useState(initialNotes);
  const [totalCount, setTotalCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [isBusy, setIsBusy] = useState(true);
  const [date, setDate] = useState('');
  const noteListRef = useRef();
  const perPage = 20;

  useEffect(() => {
    getRecords();
  }, [currentPage]);

  const getRecords = async (selectedDate = null) => {
    console.log("getting records!");
    setIsBusy(true);
    try {
      let url = '/api/note/pp/';
      const params = new URLSearchParams({
        page: currentPage,
        ...(selectedDate && { date: selectedDate }),
      });
      
      const response = await fetch(`${url}?${params}`);
      if (!response.ok) throw new Error('Failed to fetch notes');
      const data = await response.json();

      console.log("results " + data.results);
      setNotes(data.results.map(note => ({
        ...note,
        created_date: Date.parse(note.created_date)
      })));

      setTotalCount(data.count);
      setIsBusy(false);
    } catch (err) {
      console.error(`Error: ${err}`);
      handleApiError(err)
    }
  };

  const handlePageChange = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  return (
    <div>
      <div className="container" dir="ltr">
        <Pagination className="mt-3 justify-content-center">
          <Pagination.First onClick={() => handlePageChange(1)} />
          <Pagination.Prev onClick={() => handlePageChange(Math.max(1, currentPage - 1))} />
          <Pagination.Item>{currentPage}</Pagination.Item>
          <Pagination.Next onClick={() => handlePageChange(currentPage + 1)} />
          <Pagination.Last onClick={() => handlePageChange(Math.ceil(totalCount / perPage))} />
        </Pagination>
        <NoteList
          ref={noteListRef}
          notes={notes}
          isBusy={isBusy}
          hideEdits={true}
          showArchived={false}
          refreshNotes={getRecords}
        />
      </div>
    </div>
  );
}

// nuxt-front/pages/pp.vue
<template>
  <div>

    <div class="container" dir="ltr">
      <b-pagination
        v-model="currentPage"
        :total-rows="totalCount"
        :per-page="perPage"
        aria-controls="notesListt"
        class="mt-3"
        align="center"
        @input="getRecords()"
      ></b-pagination>

      <NoteList
        @refresh="getRecords()"
        :notes="notes"
        :isBusy="isBusy"
        ref="noteList"
        :hideEdits="true"
        :showArchived="showArchived"
      ></NoteList>
    </div>

  </div>
</template>

<script>
export default {
  props: ["notes"],
  data() {
    return {
      notes: "",
      totalCount: 0,
      perPage: 20,
      currentPage: 1,
      isBusy: true,
       date: ""
    };
  },
    methods: {
    getRecords: async function (date = null) {
      console.log("getting records!");
      this.isBusy = true;
      try {
        let url = "/api/note/pp/";
        const response = await this.$axios.$get(url, {
          params: {
            page: this.currentPage,
            date: date,
          },
        });

        console.log("results  "+response.results);

        this.notes = response.results;

        for (const element of this.notes) {
          element["created_date"] = Date.parse(element["created_date"]);
        }

        this.totalCount = response.count;
        this.isBusy = false;
      } catch (err) {
        console.log(`err: ${err}`);
        let handler = new ResponseHandler();
        handler.handle(err, this);
      }
    },
    mounted() {
      this.getRecords();
    },
  },
};
</script>

<style></style>
