// next-front/app/list/page.jsx
'use client';

import { useState, useContext, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button, Modal, Form } from 'react-bootstrap';
import { NoteListContext, ToastContext } from '../layout';
import { fetchWithAuth } from '../lib/api';

export default function CategoryList() {
  const [newListName, setNewListName] = useState('');
  const [showModal, setShowModal] = useState(false);
  const noteLists = useContext(NoteListContext);
  const showToast = useContext(ToastContext);

  useEffect(() => {
    window.dispatchEvent(new Event('updateNoteLists'));
  }, []);

  const archiveTopic = async (topicId) => {
    try {
      window.dispatchEvent(new CustomEvent('showWaitingModal', { detail: { title: 'Waiting for server response' } }));
      const response = await fetchWithAuth(`/api/note/list/archive/${topicId}/`, { method: 'GET' });
      if (!response.ok) throw new Error('Failed to archive topic');
      window.dispatchEvent(new Event('hideWaitingModal'));
      window.dispatchEvent(new Event('updateNoteLists'));
    } catch (err) {
      window.dispatchEvent(new Event('hideWaitingModal'));
      showToast('Error', 'Failed to archive topic', 3000, 'danger');
    }
  };

  const unArchiveTopic = async (topicId) => {
    try {
      window.dispatchEvent(new CustomEvent('showWaitingModal', { detail: { title: 'Waiting for server response' } }));
      const response = await fetchWithAuth(`/api/note/list/unarchive/${topicId}/`, { method: 'GET' });
      if (!response.ok) throw new Error('Failed to unarchive topic');
      window.dispatchEvent(new Event('hideWaitingModal'));
      window.dispatchEvent(new Event('updateNoteLists'));
    } catch (err) {
      window.dispatchEvent(new Event('hideWaitingModal'));
      showToast('Error', 'Failed to unarchive topic', 3000, 'danger');
    }
  };

  const sendNewListName = async () => {
    try {
      const response = await fetchWithAuth('/api/note/list/', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ name: newListName }),
      });
      if (!response.ok) throw new Error('Failed to create new list');
      window.dispatchEvent(new Event('updateNoteLists'));
      setShowModal(false);
      showToast('Success', 'New list created', 3000, 'success');
    } catch (err) {
      showToast('Error', 'Failed to create new list', 3000, 'danger');
    }
  };

  return (
    <div className="container">
      <div className="py-4">
        {noteLists.map((lst, lst_idx) => (
          <span key={lst.id}>
            {lst_idx > 0 && lst_idx < (noteLists.length - 1) && lst.archived !== noteLists[lst_idx - 1].archived && (
              <hr />
            )}
            <li className="list-group-item text-light rounded d-flex" style={{ backgroundColor: 'gray' }} dir="ltr">
              <div className="d-flex flex-row align-items-center">
                <Link href={`/list/${lst.slug}/`} className="text-dark">
                  {lst.name}
                </Link>
              </div>
              <div className="ms-auto">
                {lst.archived ? (
                  <Button variant="light" size="sm" onClick={() => unArchiveTopic(lst.id)}>UnArchive</Button>
                ) : (
                  <Button variant="light" size="sm" onClick={() => archiveTopic(lst.id)}>Archive</Button>
                )}
                <Button variant="info" size="sm" className="ml-2">Rename</Button>
              </div>
            </li>
          </span>
        ))}
      </div>

      <Modal show={showModal} onHide={() => setShowModal(false)}>
        <Modal.Header closeButton>
          <Modal.Title>Create New List</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <Form.Group className="d-flex flex-column">
            <Form.Label className="col-form-label align-self-start">List Name</Form.Label>
            <Form.Control
              type="text"
              value={newListName}
              onChange={(e) => setNewListName(e.target.value)}
            />
          </Form.Group>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={() => setShowModal(false)}>
            Cancel
          </Button>
          <Button variant="primary" onClick={sendNewListName}>
            Create
          </Button>
        </Modal.Footer>
      </Modal>

      <div className="text-center m-4">
        <Button variant="primary" className="p-3" onClick={() => setShowModal(true)}>
          Create New List
        </Button>
      </div>
    </div>
  );
}

// nuxt-front/pages/list/index.vue
<template>
  <div class="container">
    <div class="py-4">
      <span
        v-for="(lst,lst_idx) in $store.state.noteLists"
        :key="lst.id"
      >
      <div v-if="lst_idx > 0 && lst_idx < ($store.state.noteLists.length -1) && lst.archived !== $store.state.noteLists[lst_idx - 1].archived">
        <hr />
      </div>
        <li
          class="list-group-item text-light rounded d-flex"
          style="background-color: gray"
          dir="ltr"
        >
          <div class="d-flex flex-row align-items-center"> <nuxt-link class="text-dark" :to="'/list/' + lst.slug + '/'" >{{ lst.name }}</nuxt-link></div>

          <div class="ml-auto">
            <button v-if="lst.archived" @click="unArchiveTopic(lst.id)" class="btn btn-sm">UnArchive</button>
            <button v-if="!lst.archived" @click="archiveTopic(lst.id)" class="btn btn-sm">Archive</button>
            <button class="btn btn-info btn-sm">rename</button>
          </div>
        </li>
      </span>
    </div>

    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">ایجاد لیست جدید</h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <form id="createList" action="{% url 'store-list' %}" method="POST">
            {% csrf_token %}
            <div class="modal-body">
              <div class="form-group d-flex flex-column">
                <label
                  for="recipient-name"
                  class="col-form-label align-self-start"
                  >نام لیست</label
                >
                <input
                  type="text"
                  class="form-control"
                  id="recipient-name"
                  for="createList"
                  name="list_name"
                />
              </div>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal"
              >
                لغو
              </button>

              <button type="submit" for="createList" class="btn btn-primary">
                ایجاد
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <b-modal
      ref="create-list-modal"
      title="ایجاد لیست جدید"
      @ok="sendNewListName"
    >
      <div class="form-group d-flex flex-column">
        <label for="recipient-name" class="col-form-label align-self-start"
          >نام لیست</label
        >
        <input class="form-control" v-model="newListName" />
      </div>
    </b-modal>

    <div class="text-center m-4">
      <button
        @click="showModal()"
        type="button"
        class="btn btn-primary p-3"
        id="CreateNewList"
      >
        ایجاد لیست جدید
      </button>
    </div>
  </div>
</template>

<script>
export default {
  layout: "default",
  middleware: ["auth"],
  data() {
    return {
      // noteLists: [],
      text: "",
      newListName: "",
    };
  },
  methods: {
    archiveTopic: async function (topicId) {
      try {
        this.$root.$emit("showWaitingModal", "در انتظار پاسخ سرور");
        const response = await this.$axios.$get(
          "/api/note/list/archive/" + topicId + "/",
          {}
        );
        this.$root.$emit("hideWaitingModal");
      } catch (err) {
        this.$root.$emit("hideWaitingModal");

        let handler = new ResponseHandler();
        handler.handle(err, this);
      }
    },
    unArchiveTopic: async function (topicId) {
      try {
        this.$root.$emit("showWaitingModal", "در انتظار پاسخ سرور");
        const response = await this.$axios.$get(
          "/api/note/list/unarchive/" + topicId + "/",
          {}
        );
        this.$root.$emit("hideWaitingModal");
      } catch (err) {
        this.$root.$emit("hideWaitingModal");

        let handler = new ResponseHandler();
        handler.handle(err, this);
      }
    },
    sendNewListName: async function () {
      let response = await this.$axios.post("/api/note/list/", {
        name: this.newListName,
      });
      // this.noteLists.unshift(response.data);
      this.$root.$emit("updateNoteLists");
      this.$refs["create-list-modal"].hide();
    },
    showModal() {
      this.$refs["create-list-modal"].show();
    },
  },
  mounted: function () {
    this.$root.$emit("updateNoteLists");
  },
};
</script>

<style></style>
